name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joacoferroni/${{ secrets.DOCKER_IMAGE }}:latest
  deploy:
    needs: build-and-push

    runs-on: ubuntu-latest

    steps:
      - name: SSH connector
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME
          script: |
            echo "Log into registry"
            echo "${{ secrets.SSH_KEY }}" 
            echo "Pull image"
            docker pull joacoferroni/${{ secrets.DOCKER_IMAGE }}:latest
            echo "Stop psico fer ui image"
            docker stop psicofer_ui
            echo "Remove psicofer_ui container"
            docker rm psicofer_ui
            echo "Run Docker psicofer_ui"
            docker run -d --restart=unless-stopped \
            --name psicofer_ui -p 4200:8088/tcp joacoferroni/${{ secrets.DOCKER_IMAGE }}:latest
